include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore

linter:
  rules:
    prefer_single_quotes: true
    sort_pub_dependencies: true
    unnecessary_string_escapes: false
