name: graphql_rest_comparison
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  graphql: ^5.1.1
  http: ^0.13.4
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
